#!/bin/sh
# .claude/skills/icc-patch/scripts/list
# list: one line per patch, "DIR up|down SHAPE N LANES".
# Up means every pipe and fitting in it says up.
# Copyright (c) 2026 Brian Case. All rights reserved.
# AI contributor: Claude (Anthropic)
#
# MIT License text omitted for brevity, See LICENCE.TXT
for d in /tmp/icc-patch-*/; do
  [ -d "$d" ] || continue
  d=${d%/}; s=up
  while read -r sc p; do
    "$sc/list" | cut -d' ' -f1,2 | grep -qx "$p up" || s=down
  done < "$d/made"
  echo "$d $s $(sed -n 1p "$d/patch")"
done
